// Auto-generated by scripts/generate-curriculum.mjs
export const curriculumSidebar = [
  {
    "text": "1주차 — 웹 & JS 기초 체력 다지기",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-01-web-js/"
      },
      {
        "text": "Day 1: HTTP 기초",
        "link": "/curriculum/week-01-web-js/day-01-http-basics"
      },
      {
        "text": "Day 2: 네트워크 연결 흐름",
        "link": "/curriculum/week-01-web-js/day-02-network-flow"
      },
      {
        "text": "(참고) 웹 동작 원리",
        "link": "/curriculum/week-01-web-js/ref-web-deep"
      },
      {
        "text": "Day 3: 브라우저 렌더링(1)",
        "link": "/curriculum/week-01-web-js/day-03-rendering-1"
      },
      {
        "text": "Day 4: 브라우저 렌더링(2)",
        "link": "/curriculum/week-01-web-js/day-04-rendering-2"
      },
      {
        "text": "(참고) 브라우저 렌더링 파이프라인",
        "link": "/curriculum/week-01-web-js/ref-rendering-pipeline"
      },
      {
        "text": "Day 5: 캐시 & 리소스 힌트",
        "link": "/curriculum/week-01-web-js/day-05-cache-hints"
      },
      {
        "text": "Day 6: 인증/저장소",
        "link": "/curriculum/week-01-web-js/day-06-auth-storage"
      },
      {
        "text": "Day 7: 주간 정리",
        "link": "/curriculum/week-01-web-js/day-07-review"
      },
      {
        "text": "(참고) JS 실행 모델",
        "link": "/curriculum/week-01-web-js/ref-js-execution-model"
      }
    ]
  },
  {
    "text": "2주차 — JS 심화",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-02-js-advanced/"
      },
      {
        "text": "Day 8: Execution Context",
        "link": "/curriculum/week-02-js-advanced/day-08-execution-context"
      },
      {
        "text": "Day 9: Lexical Environment",
        "link": "/curriculum/week-02-js-advanced/day-09-lexical-environment"
      },
      {
        "text": "Day 10: Scope Chain / Closure",
        "link": "/curriculum/week-02-js-advanced/day-10-scope-closure"
      },
      {
        "text": "Day 11: Hoisting / TDZ",
        "link": "/curriculum/week-02-js-advanced/day-11-hoisting-tdz"
      },
      {
        "text": "Day 12: this / bind / call / apply",
        "link": "/curriculum/week-02-js-advanced/day-12-this-bind"
      },
      {
        "text": "Day 13: Prototype / Prototype Chain",
        "link": "/curriculum/week-02-js-advanced/day-13-prototype"
      },
      {
        "text": "Day 14: 주간 정리",
        "link": "/curriculum/week-02-js-advanced/day-14-review"
      },
      {
        "text": "Day 15: 비동기 & 이벤트 루프",
        "link": "/curriculum/week-02-js-advanced/day-15-async-event-loop"
      },
      {
        "text": "(참고) 클로저 & 프로토타입",
        "link": "/curriculum/week-02-js-advanced/ref-closure-prototype"
      },
      {
        "text": "(참고) 비동기 & 이벤트 루프",
        "link": "/curriculum/week-02-js-advanced/ref-async-event-loop"
      },
      {
        "text": "(참고) 데이터 & 함수형 사고",
        "link": "/curriculum/week-02-js-advanced/ref-data-functional"
      }
    ]
  },
  {
    "text": "3주차 — TypeScript + DOM & 성능",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-03-typescript-dom/"
      },
      {
        "text": "Day 16: TypeScript Basic",
        "link": "/curriculum/week-03-typescript-dom/day-16-typescript-basic"
      },
      {
        "text": "Day 17: Type Inference & Type System",
        "link": "/curriculum/week-03-typescript-dom/day-17-type-inference"
      },
      {
        "text": "Day 18: Generic",
        "link": "/curriculum/week-03-typescript-dom/day-18-generic"
      },
      {
        "text": "Day 19: Utility Types",
        "link": "/curriculum/week-03-typescript-dom/day-19-utility-types"
      },
      {
        "text": "Day 20: DOM",
        "link": "/curriculum/week-03-typescript-dom/day-20-dom"
      },
      {
        "text": "Day 21: Event",
        "link": "/curriculum/week-03-typescript-dom/day-21-event"
      },
      {
        "text": "Day 22: Browser Performance",
        "link": "/curriculum/week-03-typescript-dom/day-22-browser-performance"
      },
      {
        "text": "Day 23: TypeScript + DOM 실전",
        "link": "/curriculum/week-03-typescript-dom/day-23-typescript-dom-practice"
      },
      {
        "text": "(참고) TypeScript Deep Dive",
        "link": "/curriculum/week-03-typescript-dom/ref-typescript-deep"
      },
      {
        "text": "(참고) DOM & 성능 실전",
        "link": "/curriculum/week-03-typescript-dom/ref-dom-performance"
      }
    ]
  },
  {
    "text": "4주차 — 네트워크 & 렌더링 전략",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-04-network-perf/"
      },
      {
        "text": "Day 24: Fetch",
        "link": "/curriculum/week-04-network-perf/day-24-fetch"
      },
      {
        "text": "Day 25: REST API",
        "link": "/curriculum/week-04-network-perf/day-25-rest-api"
      },
      {
        "text": "Day 26: Authentication",
        "link": "/curriculum/week-04-network-perf/day-26-authentication"
      },
      {
        "text": "Day 27: CSR",
        "link": "/curriculum/week-04-network-perf/day-27-csr"
      },
      {
        "text": "Day 28: SSR & Hydration",
        "link": "/curriculum/week-04-network-perf/day-28-ssr-hydration"
      },
      {
        "text": "Day 29: Core Web Vitals",
        "link": "/curriculum/week-04-network-perf/day-29-core-web-vitals"
      },
      {
        "text": "Day 30: Resource Optimization",
        "link": "/curriculum/week-04-network-perf/day-30-resource-optimization"
      },
      {
        "text": "(참고) 데이터 통신 & 인증",
        "link": "/curriculum/week-04-network-perf/ref-data-communication-auth"
      },
      {
        "text": "(참고) 네트워크 & 성능 (고급)",
        "link": "/curriculum/week-04-network-perf/ref-network-performance-advanced"
      },
      {
        "text": "(참고) Web Vitals",
        "link": "/curriculum/week-04-network-perf/ref-web-vitals"
      }
    ]
  },
  {
    "text": "5주차 — React Rendering",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-05-react-rendering/"
      },
      {
        "text": "Day 31: React Rendering",
        "link": "/curriculum/week-05-react-rendering/day-31-react-rendering"
      },
      {
        "text": "Day 32: Reconciliation",
        "link": "/curriculum/week-05-react-rendering/day-32-reconciliation"
      },
      {
        "text": "Day 33: Virtual DOM",
        "link": "/curriculum/week-05-react-rendering/day-33-virtual-dom"
      },
      {
        "text": "Day 34: Fiber",
        "link": "/curriculum/week-05-react-rendering/day-34-fiber"
      },
      {
        "text": "Day 35: Batching",
        "link": "/curriculum/week-05-react-rendering/day-35-batching"
      },
      {
        "text": "Day 36: key",
        "link": "/curriculum/week-05-react-rendering/day-36-key"
      },
      {
        "text": "Day 37: TanStack Query",
        "link": "/curriculum/week-05-react-rendering/day-37-react-query"
      }
    ]
  },
  {
    "text": "6주차 — React Hooks & 성능",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-06-react-hooks/"
      },
      {
        "text": "Day 38: useState",
        "link": "/curriculum/week-06-react-hooks/day-38-use-state"
      },
      {
        "text": "Day 39: useEffect",
        "link": "/curriculum/week-06-react-hooks/day-39-use-effect"
      },
      {
        "text": "Day 40: dependency",
        "link": "/curriculum/week-06-react-hooks/day-40-dependency"
      },
      {
        "text": "Day 41: stale closure",
        "link": "/curriculum/week-06-react-hooks/day-41-stale-closure"
      },
      {
        "text": "Day 42: useRef",
        "link": "/curriculum/week-06-react-hooks/day-42-use-ref"
      },
      {
        "text": "Day 43: React.memo & React Profiler",
        "link": "/curriculum/week-06-react-hooks/day-43-react-memo"
      },
      {
        "text": "Day 44: useMemo",
        "link": "/curriculum/week-06-react-hooks/day-44-use-memo"
      },
      {
        "text": "Day 45: useCallback",
        "link": "/curriculum/week-06-react-hooks/day-45-use-callback"
      }
    ]
  },
  {
    "text": "7주차 — React 설계/상태/에러",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-07-react-state-error/"
      },
      {
        "text": "Day 46: Context",
        "link": "/curriculum/week-07-react-state-error/day-46-context"
      },
      {
        "text": "Day 47: Zustand / Redux",
        "link": "/curriculum/week-07-react-state-error/day-47-zustand-redux"
      },
      {
        "text": "Day 48: Custom Hook",
        "link": "/curriculum/week-07-react-state-error/day-48-custom-hook"
      },
      {
        "text": "Day 49: Controlled Component",
        "link": "/curriculum/week-07-react-state-error/day-49-controlled-component"
      },
      {
        "text": "Day 50: Error Boundary",
        "link": "/curriculum/week-07-react-state-error/day-50-error-boundary"
      },
      {
        "text": "Day 51: Suspense",
        "link": "/curriculum/week-07-react-state-error/day-51-suspense"
      }
    ]
  },
  {
    "text": "8주차 — 라우팅 · URL 상태 · 실시간 통신",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-08-routing-realtime/"
      },
      {
        "text": "SPA 라우팅 & History API",
        "link": "/curriculum/week-08-routing-realtime/08-1-spa-routing-history"
      },
      {
        "text": "URL을 상태로 (URL as State)",
        "link": "/curriculum/week-08-routing-realtime/08-2-url-as-state"
      },
      {
        "text": "실시간 통신 (WebSocket · SSE · 폴링)",
        "link": "/curriculum/week-08-routing-realtime/08-3-realtime-communication"
      },
      {
        "text": "탭 간 통신 (postMessage · storage)",
        "link": "/curriculum/week-08-routing-realtime/08-4-cross-tab-communication"
      }
    ]
  },
  {
    "text": "9주차 — 프론트 품질 (CSS · 접근성 · 테스트 · 보안)",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-09-quality/"
      },
      {
        "text": "CSS 레이아웃 & 아키텍처",
        "link": "/curriculum/week-09-quality/09-1-css-layout-architecture"
      },
      {
        "text": "시맨틱 HTML & 접근성(a11y)",
        "link": "/curriculum/week-09-quality/09-2-semantic-html-a11y"
      },
      {
        "text": "테스트 (단위 · RTL · E2E)",
        "link": "/curriculum/week-09-quality/09-3-testing"
      },
      {
        "text": "프론트 보안 (XSS · CSRF · CSP)",
        "link": "/curriculum/week-09-quality/09-4-security"
      }
    ]
  },
  {
    "text": "10주차 — 개발환경 & 빌드 툴링",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-10-tooling/"
      },
      {
        "text": "번들러 & 번들 최적화",
        "link": "/curriculum/week-10-tooling/10-1-bundler-and-bundle-optimization"
      },
      {
        "text": "ESLint & Prettier 파이프라인",
        "link": "/curriculum/week-10-tooling/10-2-eslint-prettier"
      },
      {
        "text": "Node 버전 · 환경변수",
        "link": "/curriculum/week-10-tooling/10-3-node-version-env"
      },
      {
        "text": "모노레포 & Git 설정",
        "link": "/curriculum/week-10-tooling/10-4-monorepo-git"
      },
      {
        "text": "패키지 관리 (npm · pnpm · lockfile)",
        "link": "/curriculum/week-10-tooling/10-5-package-manager"
      }
    ]
  },
  {
    "text": "11주차 — 백엔드 기초 (Node · API · 인증서버)",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-11-backend/"
      },
      {
        "text": "Node 런타임 & 서버 기초",
        "link": "/curriculum/week-11-backend/11-1-node-runtime-server"
      },
      {
        "text": "REST API 설계 심화",
        "link": "/curriculum/week-11-backend/11-2-rest-api-design-advanced"
      },
      {
        "text": "인증·인가 서버 관점 (세션 · JWT · OAuth)",
        "link": "/curriculum/week-11-backend/11-3-auth-server"
      },
      {
        "text": "BFF · API Gateway · 서버 구조",
        "link": "/curriculum/week-11-backend/11-4-bff-gateway"
      }
    ]
  },
  {
    "text": "12주차 — 데이터베이스",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-12-database/"
      },
      {
        "text": "연결 & 커넥션 풀",
        "link": "/curriculum/week-12-database/12-1-connection-pool"
      },
      {
        "text": "인덱스 & 쿼리 최적화",
        "link": "/curriculum/week-12-database/12-2-index-query"
      },
      {
        "text": "트랜잭션 & N+1",
        "link": "/curriculum/week-12-database/12-3-transaction-n1"
      }
    ]
  },
  {
    "text": "13주차 — 네트워크 · 인프라 & 배포 트러블슈팅",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-13-infra-deploy/"
      },
      {
        "text": "네트워크 심화 (TCP · TLS · HTTP/2·3 · DNS)",
        "link": "/curriculum/week-13-infra-deploy/13-1-network-deep"
      },
      {
        "text": "Nginx 리버스 프록시 · 서브도메인 · 라우팅",
        "link": "/curriculum/week-13-infra-deploy/13-2-nginx-reverse-proxy-subdomain"
      },
      {
        "text": "정적 배포 · S3 · CDN(CloudFront) · 미디어",
        "link": "/curriculum/week-13-infra-deploy/13-3-static-deploy-s3-media"
      },
      {
        "text": "Docker & CI/CD",
        "link": "/curriculum/week-13-infra-deploy/13-4-docker-cicd"
      },
      {
        "text": "실전 트러블슈팅 사례집",
        "link": "/curriculum/week-13-infra-deploy/13-5-troubleshooting-cases"
      }
    ]
  },
  {
    "text": "14주차 — 분석 · 측정 & 관측",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-14-analytics/"
      },
      {
        "text": "사용자 분석 (GA4 · Clarity · Looker)",
        "link": "/curriculum/week-14-analytics/14-1-ga4-clarity-looker"
      },
      {
        "text": "프론트 관측 (모니터링 · RUM · Sentry)",
        "link": "/curriculum/week-14-analytics/14-2-monitoring-rum-sentry"
      }
    ]
  },
  {
    "text": "15주차 — 경력 무기화",
    "collapsed": true,
    "items": [
      {
        "text": "주차 개요",
        "link": "/curriculum/week-15-career/"
      },
      {
        "text": "프로젝트 회고 ①",
        "link": "/curriculum/week-15-career/day-75-project-retrospective-1"
      },
      {
        "text": "프로젝트 회고 ②",
        "link": "/curriculum/week-15-career/day-76-project-retrospective-2"
      },
      {
        "text": "장애 경험 정리",
        "link": "/curriculum/week-15-career/day-77-incident-experience"
      },
      {
        "text": "성능 개선 경험 정리",
        "link": "/curriculum/week-15-career/day-78-performance-improvement"
      },
      {
        "text": "협업 경험 정리",
        "link": "/curriculum/week-15-career/day-79-collaboration"
      },
      {
        "text": "STAR 답변 작성",
        "link": "/curriculum/week-15-career/day-80-star-answers"
      }
    ]
  }
] as const;
